<a href="https://colab.research.google.com/github/nedokormysh/Stepik_Ai_edu_RNN/blob/week_4_PyTorch/IntroToPyTorch_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [3]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [4]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание 1

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [6]:
# ваш код здесь
res = a @ a.T

In [11]:
round(res[0, 0], 2)

1.58

In [12]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [13]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание 2

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [18]:
# ваш код здесь
np.sum(np.arange(1, 10001)**2)

333383335000

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [19]:
x = torch.rand(5, 3)
x

tensor([[0.6530, 0.7169, 0.6362],
        [0.9092, 0.5002, 0.2932],
        [0.0592, 0.4590, 0.9907],
        [0.1247, 0.4553, 0.0994],
        [0.1602, 0.4721, 0.2437]])

In [20]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [21]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.6530, 5.7169, 5.6362],
        [5.9092, 5.5002, 5.2932],
        [5.0592, 5.4590, 5.9907],
        [5.1247, 5.4553, 5.0994],
        [5.1602, 5.4721, 5.2437]])



In [22]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[1.3451, 1.1388, 0.9981, 0.4710, 0.5981],
        [1.1388, 1.1629, 0.5739, 0.3703, 0.4533],
        [0.9981, 0.5739, 1.1958, 0.3148, 0.4677],
        [0.4710, 0.3703, 0.3148, 0.2327, 0.2591],
        [0.5981, 0.4533, 0.4677, 0.2591, 0.3080]])

X*X^T  (2):
tensor([[1.3451, 1.1388, 0.9981, 0.4710, 0.5981],
        [1.1388, 1.1629, 0.5739, 0.3703, 0.4533],
        [0.9981, 0.5739, 1.1958, 0.3148, 0.4677],
        [0.4710, 0.3703, 0.3148, 0.2327, 0.2591],
        [0.5981, 0.4533, 0.4677, 0.2591, 0.3080]])



In [23]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.6687, 0.5676, 0.5030, 0.2265, 0.2920])



In [24]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [25]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-25-b9d129fd8adb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [26]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[-3.7440e+34,  4.5900e-41, -3.7440e+34],
        [ 4.5900e-41,  1.4013e-45,  0.0000e+00],
        [ 5.2574e+03,  3.1823e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 5.1299e+03,  3.1823e-41,  1.2517e+02]])


In [27]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.5653, 0.8448, 0.6006],
        [0.9598, 0.4931, 0.3007],
        [0.0834, 0.4984, 0.2971],
        [0.6903, 0.8105, 0.4752],
        [0.0093, 0.4899, 0.2202]])


In [28]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [29]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [30]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [31]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[ 1.8327,  2.2704, -1.6015],
        [-1.4078, -1.5062,  0.1722],
        [ 0.4352, -0.4756, -0.6074],
        [-0.3555,  0.2073, -0.2072],
        [ 1.2856, -1.2786, -0.9100]]) torch.Size([5, 3])


## Задание 3

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [43]:
torch.manual_seed(42)

# ваш код здесь
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [45]:
res = x + y
res[0][0]

tensor(1.3117)

In [ ]:
print(x * y) # поэлементное умножение

## Задание 4

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [53]:
res = x @ y.T
round(res[-1][-1].item(), 2)

0.49

In [ ]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга

torch.Size([1, 5, 3])


In [ ]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга

torch.Size([5, 3])


In [ ]:
a = torch.rand((1,3))
a

tensor([[0.8823, 0.9150, 0.3829]])

In [ ]:
a.squeeze(0)

tensor([0.8823, 0.9150, 0.3829])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [ ]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [ ]:
a @ b

array([70])

In [ ]:
# b @ a